<?php
/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_context_registry().
 */
function lazyadslot_context_registry() {
  return [
    'reactions' => [
      'lazyadslot' => [
        'title' => t('Lazy Loading Ad Slots'),
        'plugin' => 'lazyadslot_context_reaction',
      ],
    ],
  ];
}

/**
 * Implements hook_context_plugins().
 */
function lazyadslot_context_plugins() {
  $plugins['lazyadslot_context_reaction'] = [
    'handler' => [
      'path' => drupal_get_path('module', 'lazyadslot') . '/plugins',
      'file' => 'lazyadslot_context_reaction.inc',
      'class' => 'LazyLoadAdSlotContextReaction',
      'parent' => 'context_condition',
    ],
  ];
  return $plugins;
}

/**
 * Implements hook_page_build().
 *
 * Get all needed settings and add it to the JavaScript which will append
 * the rendered dfp tag in specified location.
 * All the visibility rules should be controlled by the context.
 */
function lazyadslot_page_build(&$page) {

  $tags = [];

  // Execute lazyadslot plugin.
  if ($plugin = context_get_plugin('reaction', 'lazyadslot')) {
    $plugin->execute();

    // Missing configuration.
    //    if (empty($plugin->lazyadslot_tags)) {
    //      return;
    //    }

    foreach ($plugin->lazyadslot_tags as $key => $values) {

      $ad_tag = $values['ad_tag'];

      // Load the DFP tag.
      $tag = dfp_tag_load($ad_tag);

      // Check for existence.
      if (empty($tag)) {
        drupal_set_message(t('Invalid dfp tag: %name', array('%name' => $ad_tag)), 'error');
        continue;
      }

      // Disabled tag.
      if (!empty($tag->disabled)) {
        continue;
      }

      // Process the tag.
      $dfp_tag = dfp_tag($ad_tag);
      $tags[$key] = $values;

      // Get the slot Display.
      $slotDisplay = render($dfp_tag);

      // Store the slot to be removed later in hook_js_alter().
      _lazyadslot_slot_to_remove($ad_tag);

      // Get the slot declaration.
      $slotDeclaration = _lazyload_get_slot_declaration($ad_tag);

      // The Ad can't be created if the declaration is not detected.
      if (empty($slotDeclaration)) {
        continue;
      }

      // Load the ads even if "initial ad load" from dfp module is disabled.
      if (variable_get('dfp_disable_init_load', 1)) {
        $slotDeclaration = str_ireplace('googletag.pubads().disableInitialLoad();', '', $slotDeclaration);
      }

      // Arraying the selectors.
      $tags[$key]['ad_placement'] = explode(PHP_EOL, $values['ad_placement']);

      // All Ad needed markup.
      $tags[$key]['renderedDfp'] = '<script>' . PHP_EOL . $slotDeclaration . PHP_EOL . '</script>' . PHP_EOL . $slotDisplay;
    }

    // Add the javascript.
    _lazyadslot_add_js($tags);
  }
}

/**
 * Helper to retrieve added js for given ad_tag slot.
 *
 * @param string $ad_tag
 *   DFP slot machinename
 * @return string
 *   JavaScript code
 */
function _lazyload_get_slot_declaration($ad_tag) {
  foreach (drupal_add_js() as $key => $value) {
    if (isset($value['data']) && !is_array($value['data']) && strstr($value['data'], 'googletag')) {
      if (preg_match('/' . 'googletag\.slots\[\"' . $ad_tag . '\"\]\s*=\s*googletag\.define[^\(]*?Slot\(' . '/', $value['data'])) {
        return $value['data'];
      }
    }
  }
}

/**
 * Helper to add the javascript code for Taboola DFP Native.
 */
function _lazyadslot_add_js($tags) {
  // Load the library.
  drupal_add_js(drupal_get_path('module', 'lazyadslot') . '/js/lazyadslot.js');

  // Add collected JS configuration.
  if (!empty($tags)) {
    drupal_add_js([
      'lazyAdSlot' => [
        'tags' => $tags,
      ],
    ], 'setting');

    // The usage.
    drupal_add_js(drupal_get_path('module', 'lazyadslot') . '/js/lazyadslot_init.js');
  }
}

/**
 * Helper to statically store the slot in order to be removed in hook_js_alter().
 *
 * @param string $ad_tag
 *   The machine name of the slot.
 * @return string $machinename
 */
function _lazyadslot_slot_to_remove($ad_tag = NULL) {
  $machinename = &drupal_static(__FUNCTION__, FALSE);
  if (!empty($ad_tag)) {
    $machinename = $ad_tag;
  }
  return $machinename;
}

/**
 * Implements hook_js_alter().
 *
 * Remove unneeded declared DFP slot.
 */
function lazyadslot_js_alter(&$javascript) {
  $ad_tag = _lazyadslot_slot_to_remove();

  // Iterate of all javascript items to get dfp slots.
  foreach ($javascript as $key => $value) {
    if (isset($value['data']) && !is_array($value['data']) && strstr($value['data'], 'googletag')) {
      if (preg_match('/' . 'googletag\.slots\[\"' . $ad_tag . '\"\]\s*=\s*googletag\.define[^\(]*?Slot\(' . '/', $value['data'])) {
        unset($javascript[$key]);
        return;
      }
    }
  }
}
