<?php
/**
 * @file
 * dennis_dfp_inline_wysiwyg.module
 *
 * Contains WYSIWYG features to insert ad slots inline into articles.
 */

define("LAZYADSLOT_WYSIWYG_PLACEHOLDER", '<div class="inline-body-placeholder"></div>');

/**
 * Implements hook_wysiwyg_include_directory().
 */
function lazyadslot_wysiwyg_wysiwyg_include_directory($type) {
  switch ($type) {
    case 'plugins':
      return 'plugins/wysiwyg';
  }
}
